name: Backend Tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.4]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage and save output
      working-directory: ./backend
      run: |
        pytest --cov=./ > pytest_output.txt

    - name: Post test results as PR comment
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const testResults = fs.readFileSync('backend/pytest_output.txt', 'utf8');
          const body = `
          ## Test Results
          \`\`\`
          ${testResults}
          \`\`\`
          `;
          await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
          })