name: pytest-coverage-commentator

on:
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set environment variables
      run: |
        echo "NEON_CONNECTION_STRING=${{ secrets.NEON_CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests without coverage (debugging step)
      run: |
        pytest tests/ --log-level=DEBUG

    - name: Build coverage file
      run: |
        pytest --cache-clear --cov=app tests/ > pytest-coverage.txt

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: pytest-coverage.txt

    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
        token: ${{ secrets.PAT_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        