name: Backend Tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.4]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        pytest --cov=./ --cov-report=xml --cov-report=html --cov-report=term
    - uses: pavelzw/pytest-action@v2
      with:
        emoji: true
        verbose: true
        job-summary: true
        click-to-expand: true
        report-title: 'Test Report'