name: Backend Tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.4]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        pytest --cov=./ --cov-report=xml --cov-report=html --cov-report=term

    - name: Generate coverage report
      working-directory: ./backend
      run: |
        coverage report
        coverage xml

    - name: Post test results as PR comment
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const coverageReport = fs.readFileSync('backend/coverage.xml', 'utf8');
          const testResults = fs.readFileSync('backend/test-results.txt', 'utf8');
          const { context } = require('@actions/github');
          const { pull_request } = context.payload;
          const body = `
          ## Test Results
          \`\`\`
          ${testResults}
          \`\`\`
          ## Coverage Report
          \`\`\`xml
          ${coverageReport}
          \`\`\`
          `;
          await github.rest.issues.createComment({
            ...context.repo,
            issue_number: pull_request.number,
            body
          });